### ISSUE TITLE
uncaught exception when invalid token is used

### ISSUE THREAD

**Issue by melanger** [UniversitaDellaCalabria/SATOSA-oidcop#3]
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/064b18d271ce406cf5af10a4766eaaf7cfadc648/satosa_oidcop/idpy_oidcop.py#L392

When an invalid access token is used (e.g. not a JWT at all, like tokens from the other OIDC frontend) at the userinfo endpoint, an exception is raised on the above line, and SATOSA responds with HTTP 500.

From the logs:

```
[WARNI]: Could not parse JWS: expected token to contain at least one dot: b'db55.........6'
[INFO ]: Unknown token format
[WARNI]: UserInfo endoint: Can't find any suitable sid/claims from stored session
[ERROR]: [urn:uuid:e2.......11] Uncaught exception
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 240, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/src/satosa/src/satosa/base.py", line 180, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 384, in userinfo_endpoint
    response = JsonResponse(proc_req["response_args"])
  File "/opt/satosa/lib/python3.9/site-packages/oidcmsg/message.py", line 631, in __getitem__
    return self._dict[item]
KeyError: 'response_args'
[ERROR]: Unknown error
Traceback (most recent call last):
  File "/src/satosa/src/satosa/base.py", line 240, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/src/satosa/src/satosa/base.py", line 180, in _run_bound_endpoint
    return spec(context)
  File "/opt/satosa/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 384, in userinfo_endpoint
    response = JsonResponse(proc_req["response_args"])
  File "/opt/satosa/lib/python3.9/site-packages/oidcmsg/message.py", line 631, in __getitem__
    return self._dict[item]
KeyError: 'response_args'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/src/satosa/src/satosa/proxy_server.py", line 148, in __call__
    resp = self.run(context)
  File "/src/satosa/src/satosa/base.py", line 258, in run
    raise SATOSAUnknownError("Unknown error") from err
satosa.exception.SATOSAUnknownError: Unknown error
```

**Comment by peppelinux** [comment]
@melanger here https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/releases/tag/v0.4.4
thank you

userinfo endpoint and token endpoint now handles in a proper way a faulty/invalid access/refresh token
