### ISSUE TITLE
Help with configuration examples

### ISSUE THREAD

**Issue by indy-independence** [UniversitaDellaCalabria/SATOSA-oidcop#48]
I'm trying to configure this plugin in satosa using the example configuration from here:
https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/example/oidcop_frontend.yaml

I get this error when trying to start:
```
Traceback (most recent call last):
  File "/usr/local/bin/satosa-saml-metadata", line 8, in <module>
    sys.exit(construct_saml_metadata())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/satosa/scripts/satosa_saml_metadata.py", line 96, in construct_saml_metadata
    create_and_write_saml_metadata(proxy_conf, key, cert, dir, valid, split_frontend, split_backend, sign)
  File "/usr/local/lib/python3.9/site-packages/satosa/scripts/satosa_saml_metadata.py", line 59, in create_and_write_saml_metadata
    frontend_entities, backend_entities = create_entity_descriptors(satosa_config)
  File "/usr/local/lib/python3.9/site-packages/satosa/metadata_creation/saml_metadata.py", line 107, in create_entity_descriptors
    frontend_modules = load_frontends(satosa_config, None, satosa_config["INTERNAL_ATTRIBUTES"])
  File "/usr/local/lib/python3.9/site-packages/satosa/plugin_loader.py", line 68, in load_frontends
    frontend_modules = _load_plugins(config.get("CUSTOM_PLUGIN_MODULE_PATHS"), config["FRONTEND_MODULES"],
  File "/usr/local/lib/python3.9/site-packages/satosa/plugin_loader.py", line 181, in _load_plugins
    instance = module_class(callback, internal_attributes, module_config, base_url,
  File "/usr/local/lib/python3.9/site-packages/satosa_oidcop/idpy_oidcop.py", line 591, in __init__
    self.app = oidcop_app(conf)
  File "/usr/local/lib/python3.9/site-packages/satosa_oidcop/core/application.py", line 22, in oidcop_application
    config = OPConfiguration(conf=conf["op"]["server_info"], domain=domain)
  File "/usr/local/lib/python3.9/site-packages/idpyoidc/server/configure.py", line 315, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/idpyoidc/server/configure.py", line 246, in __init__
    Base.__init__(
  File "/usr/local/lib/python3.9/site-packages/idpyoidc/configure.py", line 119, in __init__
    self.domain = domain or conf.get("domain", "127.0.0.1")
AttributeError: 'NoneType' object has no attribute 'get'
```

Any ideas what could be wrong?

**Comment by indy-independence** [comment]
It was problems with indentation, I think in the example the first part/level has 4 space indent and later has 2 which got a bit weird when I tried to change everything to 2 space
