### ISSUE TITLE
Error : ValueError: no space following status code

### ISSUE THREAD

**Issue by Yoroitchi** [UniversitaDellaCalabria/SATOSA-oidcop#54]
Hello,

Making an unauthorized request to satosa using satosa_oidcop result in the following message in the browser or API tools (eg Postman):
no space following status code

In the debug log file of satosa, the result appears as follow :
```
[2024-07-03 10:24:39,846] [ERROR] [satosa.proxy_server.__call__] no space following status code
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/satosa/proxy_server.py", line 150, in __call__
    return resp(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/satosa/response.py", line 48, in __call__
    start_response(self.status, self.headers)
  File "/usr/local/lib/python3.9/site-packages/cookies_samesite_compat/middleware.py", line 28, in customize_response
    return start_response(status, headers_customized, exc_info)
ValueError: no space following status code
```
According to my research, this is a common problem in WSGI application where status code of an HTTP response is missing a space in the end.
As a matter of fact in satosa_oidcop/idpy_oidc.oy, replacing all string "403" with "403 " gives the expected response.

**Comment by MdreW** [comment]
Hi @Yoroitchi , May be because the response should be "403 Forbidden"

the [rfc7230 at 3.1.2](Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing) say:

>    The first line of a response message is the status-line, consisting
>    of the protocol version, a space (SP), the status code, another
>    space, a possibly empty textual phrase describing the status code,
>    and ending with CRLF.
> 

with only  the status code the HTTP protocol is not satisfied.

Good catch @Yoroitchi ! Would you like to make the pull request?

**Comment by peppelinux** [comment]
Resolved
